import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = path.join(__dirname, '..', 'public', 'fonts');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const GOOGLE_URL = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,600&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&family=Inter:wght@400;500;600&display=swap';

async function fetchCSS() {
  const res = await fetch(GOOGLE_URL, { headers: { 'User-Agent': UA } });
  return res.text();
}

function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const subset = m[1];
    const body = m[2];
    const family = (body.match(/font-family:\s*['"]?([^;'"]+)['"]?;/) || [])[1]?.trim();
    const style = (body.match(/font-style:\s*(\w+);/) || [])[1];
    const weight = (body.match(/font-weight:\s*(\d+);/) || [])[1];
    const url = (body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/) || [])[1];
    const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim();
    if (family && url) blocks.push({ subset, family, style, weight, url, range });
  }
  return blocks;
}

function slugify(family, style, weight, subset) {
  return `${family.replace(/\s+/g, '-').toLowerCase()}-${style === 'italic' ? 'italic-' : ''}${weight}-${subset}.woff2`;
}

async function downloadFont(url, dest) {
  if (fs.existsSync(dest)) return;
  const res = await fetch(url);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(dest, buf);
  console.log('  downloaded', path.basename(dest), `(${(buf.length / 1024).toFixed(1)}KB)`);
}

async function main() {
  console.log('Fetching Google Fonts CSS…');
  const css = await fetchCSS();
  const blocks = parseBlocks(css);

  // Only keep latin and latin-ext subsets
  const wanted = blocks.filter(b => b.subset === 'latin' || b.subset === 'latin-ext');

  // Deduplicate by URL (multiple weights can share a file)
  const urlToFile = new Map();
  const urlToSubset = new Map();

  for (const b of wanted) {
    if (!urlToFile.has(b.url)) {
      const filename = slugify(b.family, b.style, b.weight, b.subset);
      urlToFile.set(b.url, filename);
      urlToSubset.set(b.url, b.subset);
    }
  }

  console.log(`Downloading ${urlToFile.size} unique font files…`);
  for (const [url, filename] of urlToFile) {
    await downloadFont(url, path.join(FONTS_DIR, filename));
  }

  // Generate @font-face CSS
  let output = '/* Self-hosted fonts — generated by scripts/download-fonts.mjs */\n';
  for (const b of wanted) {
    const filename = urlToFile.get(b.url);
    output += `/* ${b.subset} */\n@font-face {\n`;
    output += `  font-family: '${b.family}';\n`;
    output += `  font-style: ${b.style};\n`;
    output += `  font-weight: ${b.weight};\n`;
    output += `  font-display: swap;\n`;
    output += `  src: url('/fonts/${filename}') format('woff2');\n`;
    output += `  unicode-range: ${b.range};\n`;
    output += `}\n`;
  }

  const cssPath = path.join(__dirname, '..', 'src', 'styles', 'fonts.css');
  fs.writeFileSync(cssPath, output);
  console.log('Written:', cssPath);
  console.log('Done.');
}

main().catch(e => { console.error(e); process.exit(1); });
